global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'api'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['service.api:9393']

  - job_name: 'node'
    static_configs:
      - targets: ['service.node-exporter:9100']
