apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://service.loki:3100
    basicAuth: false
    editable: true
    orgId: 1
    version: 1
    jsonData:
      timeInterval: 15s
