apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://service.prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    orgId: 1
    version: 1
    jsonData:
      timeInterval: 15s
